name       : yubioath-desktop
version    : 5.0.1
release    : 17
source     :
    - https://github.com/Yubico/yubioath-desktop/archive/yubioath-desktop-5.0.1.tar.gz : c3593e6242387b85611529fb1bb8a71846cb5d8402afc07fc8b03759e6e6522a
license    : BSD-2-Clause
component  : security
summary    : Yubico Authenticator for Desktop
description: |
    Cross-platform application for generating Open Authentication (OATH) time-based TOTP and event-based HOTP one-time password codes, with the help of a YubiKey that protects the shared secrets.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5QuickControls2)
rundeps    :
    - python-pyotherside
    - qt5-graphicaleffects
    - yubikey-manager
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    install -Dm00644 $workdir/resources/yubioath-desktop.desktop $installdir/usr/share/applications/yubioath-desktop.desktop
    install -Dm00644 $workdir/resources/icons/yubioath.png $installdir/usr/share/pixmaps/yubioath.png
