name       : yubioath-desktop
version    : 5.0.2
release    : 19
source     :
    - https://github.com/Yubico/yubioath-desktop/archive/yubioath-desktop-5.0.2.tar.gz : f52e5712d67cf87ecf6554210d091bb160a11c7e9a367faee066ac4685b74d47
license    : BSD-2-Clause
component  : security
summary    : Yubico Authenticator for Desktop
description: |
    Cross-platform application for generating Open Authentication (OATH) time-based TOTP and event-based HOTP one-time password codes, with the help of a YubiKey that protects the shared secrets.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5QuickControls2)
rundeps    :
    - python-pyotherside
    - qt5-graphicaleffects
    - yubikey-manager
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    install -Dm00644 $workdir/resources/yubioath-desktop.desktop $installdir/usr/share/applications/yubioath-desktop.desktop
    install -Dm00644 $workdir/resources/icons/com.yubico.yubioath.svg $installdir/usr/share/pixmaps/com.yubico.yubioath.svg
