name       : yubioath-desktop
version    : 3.0.1
release    : 1
source     :
    - https://github.com/Yubico/yubioath-desktop/releases/download/yubioath-desktop-3.0.1/yubioath-desktop-3.0.1.tar.gz : 91a32ec635de390b312c8d8b8194b2e5ea4a453d1e4c1f5295b6654fd16176af
license    : GPL-3.0
component  : security
summary    : Yubico Authenticator for Desktop
description: |
    Yubico Authenticator for Desktop
builddeps  :
    - pkgconfig(libpcsclite)
    - pkgconfig(ykpers-1)
    - libyubikey-devel
    - pycrypto
    - python-click
    - python-pyscard
    - python-pyside-tools
    - python-setuptools
rundeps    :
    - pcsc-lite
    - pycrypto
    - python-click
    - python-pyscard
    - python-pyside-tools
    - yubikey-personalization
setup      : |
    %python_setup
install    : |
    %python_install
    install -Dm00644 resources/yubioath.desktop $installdir/usr/share/applications/yubioath.desktop
    install -Dm00644 resources/yubioath-desktop.png $installdir/usr/share/pixmaps/yubioath.png
