name       : yubioath-desktop
version    : 5.0.4
release    : 20
source     :
    - https://github.com/Yubico/yubioath-desktop/archive/yubioath-desktop-5.0.4.tar.gz : b47c8715e415b0e0ea0237e6f56d328fc8d3303a87ad89d4540d4f4a93138bd7
license    : BSD-2-Clause
component  : security
summary    : Yubico Authenticator for Desktop
description: |
    Cross-platform application for generating Open Authentication (OATH) time-based TOTP and event-based HOTP one-time password codes, with the help of a YubiKey that protects the shared secrets.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5QuickControls2)
rundeps    :
    - python-pyotherside
    - qt5-graphicaleffects
    - yubikey-manager
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    install -Dm00644 $workdir/resources/com.yubico.yubioath.desktop  $installdir/usr/share/applications/yubioath-desktop.desktop
    install -Dm00644 $workdir/resources/icons/com.yubico.yubioath.svg $installdir/usr/share/pixmaps/com.yubico.yubioath.svg
    install -Dm00644 $workdir/resources/com.yubico.yubioath.appdata.xml $installdir/usr/share/metainfo/com.yubico.yubioath.appdata.xml
