name       : yubioath-desktop
version    : 4.3.2
release    : 10
source     :
    - https://developers.yubico.com/yubioath-desktop/Releases/yubioath-desktop-4.3.2.tar.gz : 55ecc68b79d7a2bfe57ec6e74b4f6691dcb2964b6239d46a39793b34a25b1b7e
license    : GPL-3.0
component  : security
summary    : Yubico Authenticator for Desktop
description: |
    Cross-platform application for generating Open Authentication (OATH) time-based TOTP and event-based HOTP one-time password codes, with the help of a YubiKey that protects the shared secrets.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
rundeps    :
    - python-pyotherside
    - qt5-quickcontrols
    - yubikey-manager
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    install -Dm00644 $workdir/resources/yubioath-desktop.desktop $installdir/usr/share/applications/yubioath-desktop.desktop
    install -Dm00644 $workdir/resources/icons/yubioath.png $installdir/usr/share/pixmaps/yubioath.png
