name       : yubioath-desktop
version    : 4.3.0
release    : 9
source     :
    - https://developers.yubico.com/yubioath-desktop/Releases/yubioath-desktop-4.3.0.tar.gz : 69e33b67aa7724d07793195e707b58ea563852dcfabd0980f8a0ba832cae6fdd
license    : GPL-3.0
component  : security
summary    : Yubico Authenticator for Desktop
description: |
    Cross-platform application for generating Open Authentication (OATH) time-based TOTP and event-based HOTP one-time password codes, with the help of a YubiKey that protects the shared secrets.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
rundeps    :
    - python-pyotherside
    - qt5-quickcontrols
    - yubikey-manager
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    install -Dm00644 $workdir/resources/yubioath-desktop.desktop $installdir/usr/share/applications/yubioath-desktop.desktop
    install -Dm00644 $workdir/resources/icons/yubioath.png $installdir/usr/share/pixmaps/yubioath.png
