name       : yubico-authenticator
version    : 6.1.0
release    : 1
source     :
    - https://github.com/Yubico/yubioath-flutter/releases/download/6.1.0/yubico-authenticator-6.1.0-linux.tar.gz : be686148475d642027d6126ea0984578aa2c22a179a565dc24b81b72ea457417
license    : BSD-2-Clause
component  : security
summary    : Yubico Authenticator for Desktop
description: |
    Store your unique credential on a hardware-backed security key and take it wherever you go from mobile to desktop. No more storing sensitive secrets on your mobile phone, leaving your account vulnerable to takeovers. With the Yubico Authenticator you can raise the bar for security.

    The Yubico Authenticator will work with any USB or NFC-enabled YubiKeys

    The Yubico Authenticator securely generates a code used to verify your identity as you are logging into various services. No connectivity needed!

patterns   :
    - /*
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(pango)
rundeps    :
    - yubikey-manager
install    : |
    # Packager's Note: Build from source as soon as flutter is available in the repos!!!

    # Desktop and icon
    sed -i 's|\(Exec="\)@EXEC_PATH|\1/usr/share/yubioath-desktop|' linux_support/com.yubico.authenticator.desktop
    sed -i 's|\(Icon=\)@EXEC_PATH/linux_support/|\1|' linux_support/com.yubico.authenticator.desktop
    install -Dm00644 linux_support/com.yubico.authenticator.desktop $installdir/usr/share/applications/com.yubico.authenticator.desktop
    install -Dm00644 linux_support/com.yubico.yubioath.png $installdir/usr/share/pixmaps/com.yubico.yubioath.png

    # Binary
    install -Dm00755 authenticator $installdir/usr/share/yubioath-desktop/authenticator
    install -dm00755 $installdir/usr/bin
    ln -sv ../share/yubioath-desktop/authenticator $installdir/usr/bin/authenticator

    # Bundled libs
    install -dm00755 $installdir/usr/share/yubioath-desktop/lib/
    for i in lib/*; do
        install -m00644 $i $installdir/usr/share/yubioath-desktop/lib/.
    done

    # Helper assests
    install -dm00755 $installdir/usr/share/yubioath-desktop/helper/
    cp -a helper/* $installdir/usr/share/yubioath-desktop/helper/

    # Static assests
    install -dm00755 $installdir/usr/share/yubioath-desktop/data/
    cp -a data/* $installdir/usr/share/yubioath-desktop/data/

replaces   :
    - yubioath-desktop
    - dbginfo : yubioath-desktop-dbginfo
