name       : yubioath-desktop
version    : 3.1.0
release    : 3
source     :
    - https://github.com/Yubico/yubioath-desktop/releases/download/yubioath-desktop-3.1.0/yubioath-desktop-3.1.0.tar.gz : 7caae0fd3b14529476eda3a5660bc050584b298ddc3c8d1adfe221041fa5db49
license    : GPL-3.0
component  : security
summary    : Yubico Authenticator for Desktop
description: |
    Yubico Authenticator for Desktop
builddeps  :
    - pkgconfig(libpcsclite)
    - pkgconfig(ykpers-1)
    - ccid
    - libyubikey-devel
    - pycrypto
    - python-click
    - python-pyscard
    - python-pyside-tools
    - python-setuptools
rundeps    :
    - ccid
    - pcsc-lite
    - pycrypto
    - python-click
    - python-pyscard
    - python-pyside-tools
    - yubikey-personalization
setup      : |
    sed -i 's:Exec=yubioath:Exec=yubioath-gui:g' resources/yubioath.desktop
    %python_setup
install    : |
    %python_install
    install -Dm00644 resources/yubioath.desktop $installdir/usr/share/applications/yubioath.desktop
    install -Dm00644 resources/yubioath-desktop.png $installdir/usr/share/pixmaps/yubioath.png
