name       : yubioath-desktop
version    : 5.0.5
release    : 21
source     :
    - https://github.com/Yubico/yubioath-desktop/archive/refs/tags/yubioath-desktop-5.0.5.tar.gz : 12ed228265e18603c569cf1366af0bcf1f6ea29a314f64964b8fe28c4cb03986
license    : BSD-2-Clause
component  : security
summary    : Yubico Authenticator for Desktop
description: |
    Cross-platform application for generating Open Authentication (OATH) time-based TOTP and event-based HOTP one-time password codes, with the help of a YubiKey that protects the shared secrets.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5QuickControls2)
rundeps    :
    - python-pyotherside
    - qt5-graphicaleffects
    - yubikey-manager
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    install -Dm00644 $workdir/resources/com.yubico.yubioath.desktop  $installdir/usr/share/applications/yubioath-desktop.desktop
    install -Dm00644 $workdir/resources/icons/com.yubico.yubioath.svg $installdir/usr/share/pixmaps/com.yubico.yubioath.svg
    install -Dm00644 $workdir/resources/com.yubico.yubioath.appdata.xml $installdir/usr/share/metainfo/com.yubico.yubioath.appdata.xml
