name       : yubioath-desktop
version    : 4.1.1
release    : 5
source     :
    - git|https://github.com/Yubico/yubioath-desktop.git : yubioath-desktop-4.1.1
license    : GPL-3.0
component  : security
summary    : Yubico Authenticator for Desktop
description: |
    Yubico Authenticator for Desktop
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
rundeps    :
    - ccid
    - python3-qt5
    - python-pyotherside
    - yubikey-manager
build      : |
    %qmake
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    install -Dm00644 resources/yubioath.desktop $installdir/usr/share/applications/yubioath.desktop
    install -Dm00644 resources/icons/yubioath.png $installdir/usr/share/pixmaps/yubioath.png
