name       : yubioath-desktop
version    : 5.1.0
release    : 22
source     :
    - https://github.com/Yubico/yubioath-desktop/archive/refs/tags/yubioath-desktop-5.1.0.tar.gz : ffe5dfd3fffbaf4e43aa366c1863e7f720df2bcbe437d5baddc34f7837dfa78e
license    : BSD-2-Clause
component  : security
summary    : Yubico Authenticator for Desktop
description: |
    Cross-platform application for generating Open Authentication (OATH) time-based TOTP and event-based HOTP one-time password codes, with the help of a YubiKey that protects the shared secrets.
patterns   :
    - /*
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(dri)
rundeps    :
    - python-pyotherside
    - qt5-graphicaleffects
    - yubikey-manager
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    install -dm00755 $installdir/usr/bin/
    mv $installdir/usr/lib/yubioath-desktop $installdir/usr/bin
    rmdir $installdir/usr/lib
    install -Dm00644 $workdir/resources/com.yubico.yubioath.desktop  $installdir/usr/share/applications/yubioath-desktop.desktop
    install -Dm00644 $workdir/resources/icons/com.yubico.yubioath.svg $installdir/usr/share/pixmaps/com.yubico.yubioath.svg
    install -Dm00644 $workdir/resources/com.yubico.yubioath.appdata.xml $installdir/usr/share/metainfo/com.yubico.yubioath.appdata.xml
