name       : yubioath-desktop
version    : 4.1.4
release    : 7
source     :
    - git|https://github.com/Yubico/yubioath-desktop.git : yubioath-desktop-4.1.4
license    : GPL-3.0
component  : security
summary    : Yubico Authenticator for Desktop
description: |
    Cross-platform application for generating Open Authentication (OATH) time-based TOTP and event-based HOTP one-time password codes, with the help of a YubiKey that protects the shared secrets.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
rundeps    :
    - python-pyotherside
    - qt5-quickcontrols
    - yubikey-manager
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    install -Dm644 resources/yubioath.desktop $installdir/usr/share/applications/yubioath.desktop
    install -Dm644 resources/icons/yubioath.png $installdir/usr/share/pixmaps/yubioath.png
