name       : yubioath-desktop
version    : 4.3.3
release    : 11
source     :
    - https://developers.yubico.com/yubioath-desktop/Releases/yubioath-desktop-4.3.3.tar.gz : fec3bacf05470dc119b4ec4c077ed13b49c9052baffd98dbcd9a3f05635b0aa8
license    : BSD-2-Clause
component  : security
summary    : Yubico Authenticator for Desktop
description: |
    Cross-platform application for generating Open Authentication (OATH) time-based TOTP and event-based HOTP one-time password codes, with the help of a YubiKey that protects the shared secrets.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
rundeps    :
    - python-pyotherside
    - qt5-quickcontrols
    - yubikey-manager
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    install -Dm00644 $workdir/resources/yubioath-desktop.desktop $installdir/usr/share/applications/yubioath-desktop.desktop
    install -Dm00644 $workdir/resources/icons/yubioath.png $installdir/usr/share/pixmaps/yubioath.png
